feat: Additional configuration for Google Cloud Run
hashicorp/waypoint pull request #1123
Opened 2021-02-20 13:58 UTC by matoous

Add additional configuration for Google Cloud Run.
Specifically, add options to specify connectible
CloudSQL instances, VPC Access Connector and the
type of the connector.

Reference: https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate

2021-02-20 13:58 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=1123)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=1123)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=1123).</sub>

2021-04-20 21:28 UTC, matoous commented
@krantzinator sorry for tagging you. I see you modified the target milestone for `0.3.x`. Just out of curiosity, what does it mean? Will this be merged in the future?

2021-04-20 21:43 UTC, krantzinator commented
@matoous We have not reviewed it in-depth yet but we do want to consider it for inclusion in a 0.3.x release, yes. Thank you for the contribution! We just released 0.3.1 and plan to do a couple more 0.3.x releases over this next month or so.

2021-04-20 21:48 UTC, matoous commented
Sure, no worries, just wanted to know what’s the current state. Thanks for the info!

2021-05-06 22:37 UTC, evanphx requested changes
This looks fine and I'd be happy to include it in 0.3.x. Could you add a changelog file along with the change? Check out this PR for a quick example of the format: https://github.com/hashicorp/waypoint/pull/1393.

Thanks!

2021-05-07 07:58 UTC, matoous commented
@evanphx Hi! Rebased and added entry to the change log. I amended the changes, hope that's ok.

2021-05-10 17:38 UTC, evanphx approved these changes

2021-05-10 17:39 UTC, merged