Expose `HasRegistry` bool to builder plugins, Docker doesn't pull if it doesn't have to
hashicorp/waypoint pull request #1198
Opened 2021-03-15 17:08 UTC by mitchellh

The main motivation for this PR is to enable a workflow where Waypoint is using an externally built image (such as from CI) without requiring `docker` or any privileges/namespaces even in a Dockerless environment (i.e. with `img`). 

Since `img` still requires user namespaces and user namespaces aren't enabled by default on most hosted K8S platforms, this enables a working Waypoint experience if the above two conditions are met, guaranteed. 

To make this work, I've exposed a named variable `HasRegistry` that builders can opt-in for (via the typical argmapper DI stuff, see the Docker implementation in this PR) to determine if there is a registry configured.

For Docker, if the CEB injection is disabled AND there is no registry, we don't pull at all.

2021-03-15 17:20 UTC, evanphx requested changes
While I do like love pushing the envelope, probably the arg should be a named structure.

2021-03-15 17:20 UTC, evanphx commented on builtin/docker/pull/builder.go
> +}) (*wpdocker.Image, error) {
While nifty, I think we should probably pull this out as a named struct. The pattern of arg structs in grpc is well known and it's less surprising than seeing an anon struct in a params listing.

2021-03-16 16:57 UTC, evanphx approved these changes

2021-03-18 19:16 UTC, mitchellh commented
So turns out this doesn't work at all with real plugins cause we don't support named primitive types across the plugin boundary. Working on that now in waypoint-plugin-sdk.

2021-03-18 22:13 UTC, briancain approved these changes

2021-03-18 22:21 UTC, merged