Specify number of deployments to retain when pruning during release
hashicorp/waypoint pull request #1230
Opened 2021-03-24 20:38 UTC by mitchellh

Fixes #988 

This adds two new CLI flags to `up` and `release`: 

* `-prune` to disable pruning completely (not recommended, defaults true to prune)
* `-prune-retain` to specify how many existing deployments to retain, defaults to "2".

The `-prune-retain` flag can be set to 0 to remove all previous deploys.

This only allows setting this via the CLI (or very raw API) today. In the future we should investigate exposing this more completely in waypoint.hcl files, the UI, etc. But this gets in a minimal solution to help the folks in #988.

2021-03-24 21:18 UTC, evanphx requested changes
Clarify the logic and wording around it being the unrelease deployments, not total deployments.

2021-03-24 21:18 UTC, evanphx commented on website/content/docs/lifecycle/release.mdx
> +By default, Waypoint keeps the past two deployments at all times for
```suggestion
By default, Waypoint keeps just one previous deployment for
```

2021-03-24 21:18 UTC, evanphx commented on internal/cli/releases_create.go
> +				"then this will default to 2 on the server. If you want to prune " +
```suggestion
				"then this will default to 1 on the server. If you want to prune " +
```

2021-03-24 21:18 UTC, evanphx commented on internal/cli/up.go
> +				"then this will default to 2 on the server. If you want to prune " +
```suggestion
				"then this will default to 1 on the server. If you want to prune " +
```

2021-03-24 21:18 UTC, evanphx commented on internal/runner/operation_release.go
> +			retain = int(op.Release.PruneRetain)
```suggestion
			retain = int(op.Release.PruneRetain) + 1 // add 1 to make this the total number
```

2021-03-24 23:25 UTC, briancain approved these changes
🍇 👍🏻

2021-03-25 01:15 UTC, evanphx approved these changes

2021-03-25 15:58 UTC, merged