website: bring nested-node in scope for sub-pages
hashicorp/waypoint pull request #1466
Opened 2021-05-12 14:26 UTC by kylemac

closes #1462  (hopefully)

@evanphx - my initial test in `/content/docs/index.mdx` showed things were working but then I realized I hadn't put the `<NestedNode>` component in scope for `/commands` or `/plugins`. This fixes that issue but let me know if thats not exactly the issue you were observing.

2021-05-12 17:46 UTC, evanphx commented
This doesn't seem to work, I still get the same HTML as shown in #1462. Could the markdown be confusing things?

2021-05-12 17:48 UTC, evanphx commented
Could the issue be that `<NestedNode>` is used in an .mdx partial?

2021-05-12 17:53 UTC, evanphx commented
Ok, I did some testing and `<NestedNode>` works `content/plugins/aws-ecs.mdx` fine, but doesn't work on the partials that are included into there.

2021-05-12 17:59 UTC, evanphx requested changes
Doesn't seem to work in partials still.

2021-05-12 19:18 UTC, kylemac commented
@evanphx ah okay. partials are a different story. one of the limitations of partials is that we don't yet support MDX components. that said, lemme dig in a little bit and see if there's a workaround for this

2021-10-06 17:07 UTC, evanphx commented
@kylemac We're going to close this because we need it on partials. When/if that comes back around, we'll make a new PR or reopen this one.

2021-10-06 17:07 UTC, closed without merging