Convert Docker to use new SDK Resource Manager
hashicorp/waypoint pull request #1477
Opened 2021-05-17 17:29 UTC by mitchellh

This converts the Docker plugin to use the new [resource manager library](https://github.com/hashicorp/waypoint-plugin-sdk/pull/29) in the SDK. This will improve error handling and makes the code a bit more structured. There is no other functionality changes in this PR.

2021-05-18 02:02 UTC, krantzinator approved these changes

2021-05-18 13:17 UTC, izaaklauer approved these changes

2021-05-18 14:53 UTC, briancain requested changes
NIce! Looks good, I just had a request to update some of the output 😄 But otherwise works well for me 🎉 🐳

2021-05-18 14:53 UTC, briancain commented on builtin/docker/platform.go
> +			s.Done()
I _think_ Evans recent work with stepgroups is going to fix this, but I noticed  this line never resolves as Done:

![Screenshot from 2021-05-18 07-50-02](https://user-images.githubusercontent.com/810277/118673194-aaefce80-b7ad-11eb-88a1-eecb5c0ef7f2.png)

2021-05-18 14:53 UTC, briancain commented on builtin/docker/platform.go
> +			s.Done()
We could add an update here that's like:

```suggestion
			s.Update("Docker image %q up to date!", in)
			s.Done()
```

2021-05-21 16:10 UTC, briancain approved these changes
🐳 🎉

2021-05-21 18:29 UTC, merged