WIP: refactor the #page css element
hashicorp/waypoint pull request #1666
Opened 2021-06-17 15:00 UTC by sabrinako

2021-06-25 10:38 UTC, jgwhite approved these changes
This looks good to me. I didn’t go through the diff with a fine tooth comb, but did smoke-test it and didn’t spot any regressions. The new structure seems logical 👍

2021-06-28 14:45 UTC, gregone requested changes

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/_layout.scss
> +  padding-bottom: scale.$sm-3;
these need to use margin-bottom, not padding: 

<img width="1062" alt="Screen Shot 2021-06-28 at 16 29 05" src="https://user-images.githubusercontent.com/1416421/123655345-2de55980-d82f-11eb-89f9-3b1439774019.png">

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './utilities/flash';
this is much cleaner, but some of the folder structure could be improved. `utilities` should not contain components like the flash messages (even if the styles apply to an component that comes from an external addon). I'd suggest moving this under `/components`.

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './auth-page';
move this under a `/pages` directory

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './login';
move this under a /pages directory

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './input';
move under `/components`

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './onboarding';
mover under /pages

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './output-pane';
move under /components

2021-06-28 14:45 UTC, gregone commented on ui/app/styles/app.scss
> +@import './utilities/x-toggle';
move under /components

2021-06-29 09:55 UTC, gregone approved these changes

2021-06-29 13:08 UTC, merged