"waypoint user" CLI
hashicorp/waypoint pull request #1864
Opened 2021-07-14 21:45 UTC by mitchellh

This introduces a "waypoint user" CLI that is more user-oriented. This deprecates `waypoint token`.

This exposes the user system introduced in #1752 and available as part of #1831.

2021-07-15 14:22 UTC, izaaklauer approved these changes
All looks good to me. I can imagine operators wanting a `user list` command, but it doesn't need to come now.

2021-07-15 15:08 UTC, briancain requested changes
Looks good!

If we're deprecating token we should add a warning message in that command too that prints right away when invoked.
The website and UI updates could come in a separate PR though.

2021-07-15 15:08 UTC, briancain commented on internal/cli/main.go
> +		"token": {}, // replaced by "user"
Agreed, there are also a handful of places on the website that reference `waypoint token new`:
```
website/content/docs/automating-execution/index.mdx
43:- `WAYPOINT_SERVER_TOKEN`. Must be set to a Waypoint token, created with [`waypoint token new`](/commands/token-new)

website/content/docs/runner/run-manual.mdx
54:  auth token using `waypoint token new`.

website/content/docs/server/auth.mdx
54:$ waypoint token new

website/content/docs/troubleshooting.mdx
175:$ waypoint token new

website/content/commands/token-new.mdx
8:# Waypoint Token new
10:Command: `waypoint token new`
18:Usage: `waypoint token new [options]`

ui/app/components/login-token/index.hbs
5:      <pre><code id="waypoint-token-new">waypoint token new</code></pre>
```

2021-07-15 16:21 UTC, mitchellh commented
> If we're deprecating token we should add a warning message in that command too that prints right away when invoked.

I was kind of afraid to do this cause right now we ONLY output the token so its easy to pipe somewhere. Maybe I'll force send it to stderr that should fix that.

2021-07-15 16:25 UTC, mitchellh commented
I'll merge this and do the docs changes as part of the user system docs in general. There's a lot there.

2021-07-15 16:33 UTC, briancain approved these changes

2021-07-15 16:33 UTC, merged

2021-10-31 17:14 UTC, fr3fou commented
![image](https://user-images.githubusercontent.com/1344906/139594554-90af3438-c0c1-45e1-bfd0-3abc799cd4dc.png)
The new set of commands don't seem to be working for me (running this on my server)

2021-11-01 15:05 UTC, briancain commented
Hey there @fr3fou - could you please open a new issue? We'll be able to help triage what's going on there better, thanks!