-auto-approve
hashicorp/waypoint pull request #1978
Opened 2021-08-03 22:56 UTC by biofool

it's mandatory CLI: v0.4.2

2021-08-03 22:56 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=1978)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=1978)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=1978).</sub>

2021-08-03 23:06 UTC, briancain requested changes
Hey there! Thanks for catching this in our docs. I've left a few PR fixes that should go along with it. Also if you could, please sign our CLA. Thank you!

2021-08-03 23:06 UTC, briancain commented on website/content/docs/getting-started.mdx
>  ```shell-session
```suggestion
When you are done, run `destroy` to remove the application from Docker.
Notice that the `destroy` command requires confirmation to run.

```shell-session
```

2021-08-03 23:06 UTC, briancain commented on website/content/docs/getting-started.mdx
> +$ waypoint destroy  -auto-approve```
```suggestion
$ waypoint destroy  -auto-approve
```
```

2021-08-03 23:09 UTC, biofool commented
Glad to help out.

2021-08-04 16:08 UTC, briancain approved these changes

2021-08-04 16:08 UTC, briancain commented on website/content/docs/getting-started.mdx
> +$ waypoint destroy  -auto-approve
```suggestion
$ waypoint destroy -auto-approve
```

2021-08-04 17:34 UTC, merged