Allow separate configuration of ELB subnets
hashicorp/waypoint pull request #2205
Opened 2021-09-02 21:24 UTC by izaaklauer

Prior to this PR, you could specify a set of subnets that would be used for the ALB and the ECS service. A common vpc configuration though is to put ALBs in public subnets, and keep app instances isolated in private subnets behind a nat gateway.

To facilitate that configuration, this PR adds a new `subnets` config field under the `ALB` config. Internally, it also splits the `subnet` resources into two separate `serviceSubnets` and `albSubnets` resources.

### AssignPublicIP

One loosely-related change included here too - one main reason to have app instances in a private subnet is to make it harder for the internet to ingress directly to the app. Prior to this change, all ECS instances were given public IPs, which violates the spirit of isolating the apps in a private subnet.

To fix that, this change also introduces an "assign_public_ip" field, which was commented-out before. It defaults to true, because instances in a subnet without a nat gateway (including the default subnets when not configured otherwise) need it to egress to public ECR to pull their containers.

In the future, we could notice when `assign_public_ip` is unset, check the configuration of the specified subnets to see if its route table includes a default route to a nat gateway, and only assign a public IP if it does not.

2021-09-02 21:58 UTC, izaaklauer commented on builtin/aws/ecs/platform.go
> +	AssignPublicIp *bool `hcl:"assign_public_ip,optional"`
Using a *bool so we can potentially set a clever default in the future if this value is unset.

2021-09-02 23:04 UTC, evanphx requested changes
Just a couple of minor things.

2021-09-03 12:41 UTC, izaaklauer commented on builtin/aws/ecs/platform.go
> +		docs.Default("true"),
Done!

2021-09-03 12:42 UTC, izaaklauer commented on builtin/aws/ecs/platform.go
> +			resource.WithCreate(p.resourceServiceSubnetsDiscover),
The subnet resources haven't showed up in any released version yet - I only merged it into main the other day. So it's probably backwards incompatible with main, but not for any of our users.

2021-09-03 15:02 UTC, briancain approved these changes
Nice! 👍🏻 Makes sense

2021-09-07 13:35 UTC, merged