ui: (wip) added component for docker image/tag
hashicorp/waypoint pull request #2352
Opened 2021-09-24 20:54 UTC by sabrinako

#1520

2021-10-01 10:12 UTC, jgwhite commented
I tested this with a kubernetes deploy config and got the following:

<img width="1360" alt="CleanShot 2021-10-01 at 12 06 55@2x" src="https://user-images.githubusercontent.com/34030/135603486-360d4c95-bd7e-4456-8afa-bb61a7746d50.png">

Does the Kubernetes plugin still need updated to thread this info through?

2021-10-01 10:14 UTC, jgwhite commented
What this looks like when the status report is still pending:

<img width="1360" alt="CleanShot 2021-10-01 at 12 07 46@2x" src="https://user-images.githubusercontent.com/34030/135603697-13acda25-baec-4d98-a2dd-27c60ffa649f.png">

2021-10-01 11:24 UTC, jgwhite commented on ui/app/components/container-image-tag/index.ts
> +    let container = this.args.statusReport.resourcesList.find((r) => r.type === 'container');
I’m realizing that this method of digging up the image reference isn’t general enough. On the resource detail page (which I wrote) it only works for Kubernetes pods, and here it only works for Docker containers. We should collaborate a general approach to this.

2021-10-01 11:48 UTC, jgwhite commented on ui/app/components/container-image-tag/index.ts
> +    let container = this.args.statusReport.resourcesList.find((r) => r.type === 'container');
I tried traversing everything in `statusReport.resourcesList` in search of `image` fields, this does get us what we want, but also some stuff we don’t want.

![image](https://user-images.githubusercontent.com/34030/135614968-671cadb4-91f8-467c-b600-795ec66c5302.png)

Here’s roughly what that approach would look like: https://github.com/hashicorp/waypoint/commit/cfbef23817ec7e6eabd9e30c9c8ec6ac5f93da98

2021-10-01 12:12 UTC, jgwhite commented on ui/app/components/meta-table/index.hbs
> +      {{#if @statusReport}}
Given that this component is representing data from a status report, what do you think about calling it something more explicit like `<StatusReportMetaTable>`?

2021-10-01 12:12 UTC, jgwhite commented on ui/app/components/meta-table/index.hbs
> +          <td>
You can use a [row-scoped table header](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-scope) here, if you like.

```suggestion
          <th scope="row">
```

2021-10-01 12:12 UTC, jgwhite commented on ui/app/components/meta-table/index.ts
> +export default class OverviewTable extends Component<OverviewTableArgs> {
If you’d rather not keep this class name in sync with the filename, you can export an anonymous class.

```suggestion
export default class extends Component<OverviewTableArgs> {
```

2021-10-01 12:12 UTC, jgwhite commented on ui/app/components/meta-table/index.ts
> +  }
I’d suggest deleting this, since it’s not doing any additional work.

```suggestion
```

2021-10-01 12:48 UTC, jgwhite commented
By the way: I love how you’ve structured the “How to test” instructions. Going to steal that format going forward. Hope you don’t mind!

2021-10-01 12:57 UTC, jgwhite commented on ui/app/components/meta-table/index.ts
> +interface OverviewTableArgs {
I quite like to call these just `Args`, that way I don’t need to rename the type if I rename the component.

2021-10-01 15:19 UTC, sabrinako commented on internal/server/gen/server.pb.go
> +// 	protoc        v3.17.3
Whoops, no I didn't, I'll fix this!

2021-10-04 11:43 UTC, gregone approved these changes
LGTM, just one minor comment

2021-10-04 11:43 UTC, gregone commented on ui/app/components/container-image-tag/index.ts
> +class ImageRef {
For consistency with the structure of other files, could we move the `ImageRef` class definition above the Component class?

2021-10-04 12:12 UTC, jgwhite requested changes
Looking good. Just a few minor suggestions.

2021-10-04 12:12 UTC, jgwhite commented on ui/app/components/container-image-tag/index.ts
> +export default class DockerImageBadge extends Component<Args> {
Shall we make the class name match the filename?

```suggestion
export default class ContainerImageTag extends Component<Args> {
```

Or we could drop the class name altogether like:

```suggestion
export default class extends Component<Args> {
```

2021-10-04 12:12 UTC, jgwhite commented on ui/tests/integration/components/status-report-meta-table-test.ts
> +  test('it renders', async function (assert) {
I’d be tempted to split this test in two: one for the happy path and one for the empty state.

2021-10-04 12:12 UTC, jgwhite commented on ui/app/components/status-report-meta-table/index.hbs
> +<div class="artifact-overview">
There are a few localizable strings in this file. Could we add them to `en-us.yaml`?

2021-10-05 09:53 UTC, jgwhite approved these changes
🥳

2021-10-05 14:31 UTC, merged