Do not add ODR profile to job if profile is empty
hashicorp/waypoint pull request #3062
Opened 2022-03-03 14:53 UTC by izaaklauer

Currently, if you have a default runner profile but no project-specific target, the waypoint server fails the job with the following error: `no runner profile name or id specified`. This is because the client's `waypointHCL.ConfigRunner()` is returning non-nil, but the profile field is an empty string, so the job is getting a runner profile assigned (but with an empty profile string).

The server is expecting a nil odr profile on a job to mean "no preference" [here](https://github.com/hashicorp/waypoint/blob/ff4406443d64d5f16812bef32d8b4428656aae6e/internal/server/singleprocess/service_job.go#L171), not an assigned profile with an empty string.

This fixes the problem by not assigning an odr profile to the job unless the profile name is actually set.

2022-03-03 15:54 UTC, catsby approved these changes
LGTM, though I did not test.

I think we should add a changelog for this if this is a "bug" that has been released. If this kind of profile targeting is not yet released then probably ok without one

2022-03-03 19:43 UTC, xiaolin-ninja requested changes
I can't find that error message you're referring to could you drop a link or how to reproduce?

Right now there is a check in `remoteOpPreferred` for whether the profile is an empty string: https://github.com/hashicorp/waypoint/blob/main/internal/client/runner.go#L116. The job should run locally if `runnerCfg.Profile` is empty and there is no default, otherwise it should grab the default. So this fix on the job isn't necessary, unless we want to refactor this logic.

2022-03-03 20:29 UTC, xiaolin-ninja commented
I ran some tests with a runner stanza but no profile set in the configs, and traced it through debugger... when it [hits the server ](https://github.com/hashicorp/waypoint/blob/ff4406443d64d5f16812bef32d8b4428656aae6e/internal/server/singleprocess/service_job.go#L171), `job.OndemandRunner` is correctly nil and it goes through the flow to pull a default ODR. In the case where there's no default profile, it goes local. So I wasn't able to reproduce this.

2022-03-04 00:05 UTC, xiaolin-ninja approved these changes
After discussion, we realized this is fixed in targetable runners 2, but this PR is separate because it needs to be good for Alpha.

Also before anyone says anything, I requested Izaak to nest the ifs for label-based targeting. :P

2022-03-04 00:05 UTC, merged