Stage content for Dev Portal
hashicorp/waypoint pull request #3161
Opened 2022-03-30 21:57 UTC by topfunky

This PR modifies content to be rendered in the Developer Portal. This is a long lived draft PR until we are ready to launch.

Modifications include:

- Remove mention of HashiCorp Learn (reference tutorials instead)
- Fix images and code snippets to fit within the new layout
- Rearrange content and menus where necessary

2022-04-07 17:48 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=3161)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=3161)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**1** out of **2** committers have signed the CLA.

- [x] topfunky
- [ ] hashibot-web

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=3161).</sub>

2022-04-08 20:56 UTC, karl-cardenas-coding commented
I validated that no documentation pages are referencing HashiCorp learn. 👍🏼

2022-05-18 19:28 UTC, briancain commented
Is this still a valid PR @topfunky ?

2022-05-18 19:29 UTC, topfunky commented
Yes, this is still relevant and is used by the Marketing web dev team.

2022-05-18 19:30 UTC, briancain commented
Thank you! 😄

2022-09-21 18:16 UTC, tunzor requested changes
One last mention of Learn to be removed - otherwise 👍

2022-09-21 18:16 UTC, tunzor commented on website/content/plugins/aws-ecs.mdx
>  -> For a step by step tutorial, visit [HashiCorp
```suggestion
-> For a step by step guide, visit [this AWS ECS
```

2022-09-21 18:16 UTC, tunzor commented on website/content/plugins/aws-ecs.mdx
> +Learn](https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/deploy-aws).
```suggestion
tutorial](https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/deploy-aws).
```

2022-09-21 18:26 UTC, tunzor approved these changes

2022-09-21 18:43 UTC, merged