docs: Waypoint unification work (dev-portal)
hashicorp/waypoint pull request #3215
Opened 2022-04-12 21:32 UTC by karl-cardenas-coding

This PR is for the Waypoint unification work. 

Asana [task](https://app.asana.com/0/1201979547919485/1201981221986512)

2022-04-13 20:24 UTC, karl-cardenas-coding commented
The end result of the unification is one learn tutorial that will be deprecated. The input variables [tutorial](https://learn.hashicorp.com/tutorials/waypoint/input-variables?in=waypoint/configuration). Right now the content is duplicate with the doc page.

2022-04-13 21:18 UTC, BrandonRomano approved these changes
Has my approval by way of it building successfully / everything looking in good working order... Thanks @karl-cardenas-coding 💯 

I'll defer the content review to @tunzor / @topfunky.

2022-04-14 13:18 UTC, tunzor approved these changes

2022-04-14 13:18 UTC, tunzor commented on website/content/docs/getting-started/index.mdx
> +Kubernetes-focused documentation, see the
You were going to drop the "detailed kubernetes-focused documentation" line right?

2022-04-14 18:12 UTC, topfunky requested changes
Originally the one page quick start was a key part of the onboarding and it still receives `1,000` pageviews a month, which is about 3% of all Waypoint traffic.

I talked to Mitchell and he was in favor of keeping a five minute quick start of some kind, then sending people to the full tutorial after. Could we keep the one page quick start in here somewhere?

<img width="743" alt="Screen Shot 2022-04-14 at 11 06 52 AM" src="https://user-images.githubusercontent.com/26/163451177-564d5c3d-7c4b-4429-bba1-91c3b53b6c1e.png">

2022-04-14 18:14 UTC, karl-cardenas-coding commented
> Originally the one page quick start was a key part of the onboarding and it still receives `1,000` pageviews a month, which is about 3% of all Waypoint traffic.
> 
> I talked to Mitchell and he was in favor of keeping a five minute quick start of some kind, then sending people to the full tutorial after. Could we keep the one page quick start in here somewhere?
> 
> <img alt="Screen Shot 2022-04-14 at 11 06 52 AM" width="743" src="https://user-images.githubusercontent.com/26/163451177-564d5c3d-7c4b-4429-bba1-91c3b53b6c1e.png">

I can keep the existing one, and add the other platforms as links. The thing I don't like about the existing one is that it assumes the user wants to get started with a local install and Docker.

2022-04-19 17:17 UTC, merged