Fix `docker-pull` remote operations build & push
hashicorp/waypoint pull request #3398
Opened 2022-06-01 14:30 UTC by paladin-devops

In version 0.8.2 of Waypoint, using remote operations with the `docker-pull` plugin exits without building the app. The error produced is indicated in this log message:
```
[DEBUG] waypoint.runner.agent.runner.app.example-nodejs.mapper.stdio: received EOF, stopping recv loop: job_id=01G4FSXDE0HJMNADYC94CWZ8AN job_op=*gen.Job_Build err="rpc error: code = Unavailable desc = error reading from server: read unix @->/kaniko/tmp/plugin25197406: read: connection reset by peer
```

This PR corrects that problem by updating the OCI registry that's created to align with the `registry` stanza details. The Docker context is now also explicitly provided to Kaniko.

#3394 has more details on the issue with remote operations. [This](https://gist.github.com/paladin-devops/e3cb17ec243a592af38c1a4505ca731d) is a gist of the build log and `waypoint.hcl` where I tested this out.

2022-06-02 19:11 UTC, briancain requested changes
Minor comment from me! Otherwise looks pretty straight forward 😄

2022-06-02 19:11 UTC, briancain commented on builtin/docker/pull/kaniko.go
> +	var insecure bool
Instead of the bool here for using it later, could we rely on `ai.Insecure` again?

2022-06-02 20:53 UTC, briancain approved these changes
Code looks good to me! 👍🏻

2022-06-03 17:41 UTC, demophoon requested changes
This looks good and remote building and pushing appear to work. However when testing this out it looks like we are still relying on docker for tagging images built with kaniko on remote runners.

```
✓ Running push build v2
❌ Tagging Docker image: registry-service/demophoon/nodejs-example:latest => registry-service/demophoon/nodejs-example:latest
! unable to tag image:Cannot connect to the Docker daemon at
  unix:///var/run/docker.sock. Is the docker daemon running?
```

I think this is automatically handled via kaniko when kaniko pushes the image to the registry so we might just need to skip that step for kaniko images.

2022-06-06 17:06 UTC, demophoon approved these changes
<img src="https://media0.giphy.com/media/xjZtu4qi1biIo/giphy.gif"/>

2022-06-06 17:26 UTC, merged