Deprecate multiple app blocks in a waypoint.hcl
hashicorp/waypoint pull request #3466
Opened 2022-06-16 20:56 UTC by evanphx

2022-06-16 21:21 UTC, briancain approved these changes

2022-06-16 21:21 UTC, briancain commented on internal/config/validate.go
> +const AppeningHappening = "More than one app stanza within a waypoint.hcl file is deprecated, and will be removed in 0.10.\nPlease see https://discuss.hashicorp.com/waypoint/xxyyzz for more informati
👨🏻‍🍳💋

2022-06-16 21:24 UTC, mitchellh approved these changes

2022-06-22 17:08 UTC, xiaolin-ninja commented on internal/config/validate.go
> +const AppeningHappening = "More than one app stanza within a waypoint.hcl file is deprecated, and will be removed in 0.10.\nPlease see https://discuss.hashicorp.com/t/deprecating-projects-or-how-i-le
should we make this more obnoxious? like...
```suggestion
const AppeningHappening = "[DEPRECATION] More than one app stanza within a waypoint.hcl file is deprecated, and will be removed in 0.10.\nPlease see https://discuss.hashicorp.com/t/deprecating-projects-or-how-i-learned-to-love-apps/40888 for more information."
```

2022-06-22 17:17 UTC, briancain requested changes
Ahh, @evanphx - Before we merge, we should fix the unit tests. Looks like there are some legit failures with this change.

2022-06-23 18:09 UTC, briancain approved these changes

2022-06-24 21:39 UTC, merged