Fix website parameter label
hashicorp/waypoint pull request #3507
Opened 2022-06-29 19:05 UTC by HenryEstberg

Generated website plugin documentation will now put entire categories in the optional parameters section in the case where all of the parameters in the category are optional.

2022-06-29 19:05 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=3507)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=3507)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=3507).</sub>

2022-06-29 20:15 UTC, xiaolin-ninja commented on internal/cli/app_docs.go
> +	not_req := true
We use camelcase, not snakecase for variable names.
```suggestion
	notRequired := true
```

2022-06-29 20:35 UTC, xiaolin-ninja requested changes

2022-06-29 21:45 UTC, catsby commented on internal/cli/app_docs.go
> +		if f.Category {
+1 to the simplified example above where there is only 1 block where fields are appended

2022-06-29 21:54 UTC, catsby commented on internal/cli/app_docs.go
> +
```suggestion
```

looks like an editor added an extra line here

2022-06-29 23:17 UTC, HenryEstberg commented on internal/cli/app_docs.go
> +
Good catch, done

2022-06-29 23:18 UTC, HenryEstberg commented on internal/cli/app_docs.go
> +		if f.Category {
Implemented the simplified example

2022-06-29 23:36 UTC, briancain approved these changes
Looks pretty good to me! I'd remove the changelog before merge please, but I'm approving otherwise because this PR looks to be in a good state after team review! Nice job 👏🏻 🎉

2022-06-29 23:36 UTC, briancain commented on .changelog/3507.txt
> +```
So our changelog is specifically for user-facing features. Since the docs cli is for the waypoint team, I'd remove this changelog!

2022-07-01 14:10 UTC, catsby approved these changes

2022-07-01 14:17 UTC, paladin-devops approved these changes

2022-07-01 19:49 UTC, xiaolin-ninja approved these changes

2022-07-06 17:23 UTC, merged