updating the waypoint destroy help description
hashicorp/waypoint pull request #3580
Opened 2022-07-15 18:40 UTC by cicoyle

Updating the `waypoint destroy -h` description, as previously it read only destroying resources for one app, when in fact it destroys all apps/resources in the workspace. See below:

```
$ waypoint up -w=test

$ kubectl get po
NAME                                                 READY   STATUS    RESTARTS   AGE
example-nodejs-metrics-sidecar-v7-6758bf9764-qvctl   2/2     Running   0          76s
test-example-nodejs-v7-54c9fb8448-mw4nw              1/1     Running   0          20s
waypoint-runner-0                                    1/1     Running   0          3h5m
waypoint-server-0                                    1/1     Running   0          3h5m

$ waypoint destroy -w=test -auto-approve
  Performing operation locally

» Destroying releases for application 'example-nodejs-metrics-sidecar'...
✓ Running release destroy v7
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Service deleted

» Destroying deployments for application 'example-nodejs-metrics-sidecar'...
✓ Running deployment destroy v7
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Deployment deleted
Destroy successful!
  Performing operation locally

» Destroying releases for application 'test-example-nodejs'...
✓ Running release destroy v7
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Service deleted

» Destroying deployments for application 'test-example-nodejs'...
✓ Running deployment destroy v7
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Deployment deleted
Destroy successful!

$ kubectl get po
NAME                READY   STATUS    RESTARTS   AGE
waypoint-runner-0   1/1     Running   0          3h7m
waypoint-server-0   1/1     Running   0          3h7m
```

2022-07-15 20:03 UTC, briancain requested changes
This makes sense, but I think if you use the `-app` flag then it will be single app? That would be worth mentioning in the help text too!

2022-07-15 20:03 UTC, briancain commented on internal/cli/destroy.go
> +  Delete all resources created for all apps or projects in the current workspace.
I think `project` is still singular in this case

2022-07-15 22:48 UTC, briancain approved these changes

2022-07-18 12:44 UTC, paladin-devops approved these changes

2022-07-18 14:16 UTC, izaaklauer approved these changes

2022-07-18 14:17 UTC, merged