Initial set of externalized errors for artifact service
hashicorp/waypoint pull request #3940
Opened 2022-09-27 21:41 UTC by catsby

2022-09-28 18:02 UTC, izaaklauer requested changes
Looks good overall! You don't need to filter the validator responses, and added a few other comments, but great overall.

Seeing how often you `hclog.FromContext`, I kinda wish we had a version of `hcerr.Externalize` that just took the context and pulled the logger out on its own or something.

2022-09-28 20:51 UTC, catsby commented on pkg/server/singleprocess/service_artifact.go
> +		return nil, hcerr.Externalize(hclog.FromContext(ctx), err, "invalid pushed artifact request")
👍 updated in a34b6939c

2022-09-28 21:08 UTC, catsby commented on pkg/server/singleprocess/service_artifact.go
> +				status.Errorf(codes.Internal, "uuid generation failed: %s", err),
> I don't think you need to need the status.Errorf wrapping here.

Interesting, I was following the model from [#3872](https://github.com/hashicorp/waypoint/pull/3872/files#diff-48fa27c968e88112ec604f3e047d608a03c15f7c46af34a20819e36dfdda19cbR488) were we preserved the `status.Errorf` call. I thought that's what you had indicated I should do. 


> "invalid pushed artifact request"

Ah yeah that looks like a copy-paste from the request validation, I updated that in 8fbd7baa0

2022-09-28 21:40 UTC, izaaklauer commented on pkg/server/singleprocess/service_artifact.go
> +				status.Errorf(codes.Internal, "uuid generation failed: %s", err),
I think this is fine now with the updated user-facing message. 

Nit-picking on the `status.Errorf`: It's OK to do the status.Errorf, but you only need to if you want to emit a status code other than `internal`. The framework adds the the internal code for you if you emit a bare error: https://github.com/hashicorp/waypoint/blob/main/pkg/server/hcerr/hcerr.go#L36-L42

I see that what we want to do here though is add a little bit of extra internal context to the error (i.e. "uuid generation failed".) You could also do that with `errors.Wrapf` here and have the same effect. But either way is OK!

2022-09-28 21:41 UTC, izaaklauer approved these changes

2022-09-29 15:01 UTC, catsby commented on pkg/server/singleprocess/service_artifact.go
> +				status.Errorf(codes.Internal, "uuid generation failed: %s", err),
> you only need to if you want to emit a status code other than internal

Ah cool, great to know, I'll keep that in mind as I continue to add more externalization

I made those changes in 82c1ae7f8

2022-09-29 15:03 UTC, catsby commented on pkg/server/singleprocess/service_artifact.go
> +				status.Errorf(codes.Internal, "uuid generation failed: %s", err),
aaaand now I updated it to use `%w` instead of `%s` in 0d536ebe3 :P

2022-09-29 15:24 UTC, merged