core/install/helm: Allow runner install to specify helm ref
hashicorp/waypoint pull request #4202
Opened 2022-11-16 18:20 UTC by demophoon

This commit adds the `-k8s-helm-ref` flag to the runner install command to aid in testing helm changes without cutting a Waypoint-helm release by allowing Waypoint to configure which helm tarball to download by sha instead of by tag.

Fixes: #4199

2022-11-16 18:26 UTC, paladin-devops approved these changes

2022-11-16 18:26 UTC, paladin-devops commented on internal/installutil/k8s/k8s.go
> +	"github.com/hashicorp/waypoint/internal/clierrors"
Thank you for fixing the ordering here! 😄

2022-11-16 19:16 UTC, cicoyle approved these changes
This is super helpful! :rocket:

2022-11-18 16:20 UTC, catsby requested changes
We've discussed this internally and are looking at alternatives. I recommend we close this for now

2022-11-21 22:12 UTC, izaaklauer requested changes
Good idea!

2022-11-21 22:12 UTC, izaaklauer commented on internal/runnerinstall/k8s.go
> +	})
If this is mostly for our internal use, i'd vote for making it a hidden flag so we don't noisify the docs.

```suggestion
Hidden: true,
	})
```

2023-01-03 16:54 UTC, ashleemboyer commented
Hello @demophoon! 😊 This is a quick comment to let you know I'm updating this PR with main so it's up to date with the changes made in [#4277](https://github.com/hashicorp/waypoint/pull/4277).

2023-05-03 17:51 UTC, briancain commented
What's the status of this one @demophoon ?

2023-07-09 19:56 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=4202)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=4202)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**1** out of **2** committers have signed the CLA.

- [x] demophoon
- [ ] Ashlee Boyer


---
**Ashlee Boyer** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=4202).</sub>

2023-07-17 21:33 UTC, closed without merging