cli: Introduce an editor class for in-terminal edits, add `waypoint runner profile edit` command
hashicorp/waypoint pull request #4594
Opened 2023-03-27 21:07 UTC by briancain

This commit brings in a basic Editor set of functionality to allow
various CLI commands to directly editor HCL configs rather than
requiring lots of CLI flags. Commands can launch their own editor, which
will place a temp file on disk, and return the resulting edited bytes
back to be saved or submitted as the updated config

Additionaly, this pull request implements this new editor class by introducing
a new command `waypoint runner profile edit` where you can edit a runner
profiles plugin config directly in your editor without having to pass through
an existing config file on disk.

Fixes #4427

2023-03-28 18:06 UTC, evanphx requested changes

2023-03-28 18:30 UTC, briancain commented on internal/cli/editor/editor.go
> +	// TODO(briancain): Get this working properly with json and hcl
Done! I decided to use `ParseExpression` instead, which gets me the desired behavior.

2023-03-30 16:12 UTC, briancain commented on internal/cli/editor/editor.go
> +	f, err := os.CreateTemp("", prefix+"*"+suffix)
Nah, I think it's ok that it's left around, especially in the case of errors submitting the raw data to the server. Users could re-submit their config changes, and the operation system will clean up `/tmp` eventually. This is also how `kubectl edit` works too!

2023-03-30 16:53 UTC, paladin-devops approved these changes
:shipit:

2023-03-30 19:31 UTC, merged