Convert hashicorp/waypoint to GitHub Actions
hashicorp/waypoint pull request #4617
Opened 2023-04-12 19:56 UTC by hc-github-team-es-release-engineering

Pipeline migrated from [CircleCI](https://app.circleci.com/pipelines/github/hashicorp/waypoint) :tada:

## Manual steps

Perform the following steps to complete the migration:

### hashicorp/waypoint/go-tests
- [x] Ensure environment variable is updated: `ALGOLIA_API_KEY`
- [x] Ensure environment variable is updated: `GH_DOCKER_PASS`
- [x] Ensure environment variable is updated: `GH_DOCKER_USER`
- [x] Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`
- [x] Ensure environment variable is updated: `SLACK_WEBHOOK`

### hashicorp/waypoint/integration
- [x] ~Ensure secret is available: `${{ secrets.CIRCLE_CI_SSH_KEY }}`~
- [x] ~Ensure secret is available: `${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}`~
- [x] ~Ensure environment variable is updated: `ALGOLIA_API_KEY`~
- [x] ~Ensure environment variable is updated: `GH_DOCKER_PASS`~
- [x] ~Ensure environment variable is updated: `GH_DOCKER_USER`~
- [x] ~Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`~
- [x] ~Ensure environment variable is updated: `SLACK_WEBHOOK`~

### hashicorp/waypoint/integration-hcl
- [x] ~Ensure environment variable is updated: `ALGOLIA_API_KEY`~
- [x] ~Ensure environment variable is updated: `GH_DOCKER_PASS`~
- [x] ~Ensure environment variable is updated: `GH_DOCKER_USER`~
- [x] ~Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`~
- [x] ~Ensure environment variable is updated: `SLACK_WEBHOOK`~

### hashicorp/waypoint/website-mdx
- [x] ~~Ensure environment variable is updated: `ALGOLIA_API_KEY`~~
- [x] ~~Ensure environment variable is updated: `GH_DOCKER_PASS`~~
- [x] ~~Ensure environment variable is updated: `GH_DOCKER_USER`~~
- [x] ~~Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`~~
- [x] ~~Ensure environment variable is updated: `SLACK_WEBHOOK`~~

### hashicorp/waypoint/json-docs
- [x] ~~Ensure environment variable is updated: `ALGOLIA_API_KEY`~~
- [x] ~~Ensure environment variable is updated: `GH_DOCKER_PASS`~~
- [x] ~~Ensure environment variable is updated: `GH_DOCKER_USER`~~
- [x] ~~Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`~~
- [x] ~~Ensure environment variable is updated: `SLACK_WEBHOOK`~~

### hashicorp/waypoint/frontend
- [x] Ensure environment variable is updated: `ALGOLIA_API_KEY`
- [x] Ensure environment variable is updated: `GH_DOCKER_PASS`
- [x] Ensure environment variable is updated: `GH_DOCKER_USER`
- [x] Ensure environment variable is updated: `SLACK_APPROVAL_NOTIFICATION_WEBHOOK_URL`
- [x] Ensure environment variable is updated: `SLACK_WEBHOOK`

2023-04-19 18:28 UTC, dekimsey requested changes
Highlighted some of the FIXME/discussion points.

2023-04-19 18:28 UTC, dekimsey commented on .github/workflows/integration.yml
> +# FIXME: Is this CRT-able?
> FIXME: Is this CRT-able?

We are currently working on seeing if we can move this test to use the images CRT produces in `build.yml`.

2023-04-19 18:28 UTC, dekimsey commented on .github/workflows/go-tests.yml
> +  # FIXME: We already lint in integration.yml, which should we keep?
> FIXME: We already lint in integration.yml, do we need to be linting twice? Which should we keep? 

I'm thinking we can remove the one from the `integration.yml` and keep this which is doing unit testing anyway.

2023-04-21 14:38 UTC, dekimsey commented on .github/workflows/integration.yml
> +# FIXME: Is this CRT-able?
We successfully ported this code to the CRT build.yml.

2023-04-21 18:11 UTC, dekimsey commented on .github/workflows/go-tests.yml
> +  # FIXME: We already lint in integration.yml, which should we keep?
I removed the integration.yml linting in favor of this workflow

2023-04-21 18:49 UTC, dekimsey approved these changes

2023-04-24 19:25 UTC, catsby approved these changes
👍 Thank you so much!

2023-04-25 14:11 UTC, merged