Snapshot/Restore APIs
hashicorp/waypoint pull request #723
Opened 2020-10-29 02:08 UTC by mitchellh

Details are in RFC [WP-039](https://docs.google.com/document/d/1Z05NZ9ZjAyZQqD9iTHeTAN00Ke6yD9_PkbTLJUsnMAk/edit#).

Importantly, the restore is a _stage_ restore operation currently and not a full online restore. It requires the server to be restarted to complete the restore.

2020-10-30 16:32 UTC, evanphx requested changes
One minor thing about the naming of the last chunk before the trailer.

2020-11-02 22:45 UTC, briancain approved these changes
Looks good! Just left a few open questions around a few log messages to ease some debugging woes in the future, but I don't think they should block merge if the changes don't make sense :+1:

2020-11-02 22:45 UTC, briancain commented on internal/server/singleprocess/state/snapshot.go
> +	log.Info("reading bolt information and writing it into a new bolt db")
Same question here, maybe it's worth being extra explicit in the logs for where these paths are for debugging.

```suggestion
	log.Info("reading bolt information and writing it into a new bolt db", "bolt info temp path", ri.StageTempPath)
```

2020-11-02 22:45 UTC, briancain commented on internal/server/singleprocess/state/snapshot.go
> +	log.Info("removing restore data since we're done reading it")
```suggestion
	log.Info("finished reading restore data, removing now")
```

2020-11-02 22:45 UTC, briancain commented on internal/server/singleprocess/state/snapshot.go
> +	log.Warn("restore file found, will initiate database restore")
Is it worth being extra explicit here to include the file path of the restore file?

```suggestion
	log.Warn("restore file found, will initiate database restore", "path", ri.StagePath)
```

2020-11-02 23:31 UTC, briancain approved these changes

2020-11-02 23:57 UTC, merged