return error if type is ErrSentinel to signal exit codes
hashicorp/waypoint pull request #768
Opened 2020-11-06 23:57 UTC by krantzinator

Address #719 
We were neglecting to return a non-nil error when dealing with `ErrSentinel` types, which is what we use most of the time.

2020-11-07 00:34 UTC, mitchellh requested changes
Looks great! One suggestion.

2020-11-07 00:34 UTC, mitchellh commented on internal/cli/base.go
> +				return err
I think what we should do here is continue to append to finalErr, but note we got a sentinel (switch some bool to true), then at the end something like:

```go
if finalErr == nil && didErrSentinel {
  finalErr = ErrSentinal
}

return finalErr
```

The reason being: this way we attempt to run against other apps here before we exit. The idea of this function one day is that we can try multiple apps in parallel maybe (its not today).

2020-11-09 16:59 UTC, mitchellh approved these changes

2020-11-09 17:05 UTC, merged

2020-11-10 20:08 UTC, krantzinator commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~