Update docs example for multiple app stanza
hashicorp/waypoint pull request #929
Opened 2020-12-17 08:01 UTC by vebr

Hi All,

Feel free to throw any and all of this away.

- Adding example for using multiple app stanza.  I attempted to people can understand the concepts of multiple app stanza.

2020-12-17 08:01 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=929)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/waypoint?pullRequest=929)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/waypoint?pullRequest=929).</sub>

2021-02-12 22:23 UTC, krantzinator requested changes
Thank you! I made some suggestions for clarification and to match our overall writing style in docs.

2021-02-12 22:23 UTC, krantzinator commented on website/content/docs/waypoint-hcl/app.mdx
> +separate backend and frontend processes or your project is monorepo.
```suggestion
separate backend and frontend processes or with a project that is a monorepo.
```

2021-02-12 22:23 UTC, krantzinator commented on website/content/docs/waypoint-hcl/app.mdx
> +Also can be used in `waypoint build` , `deploy` , `release` and `up`
```suggestion
Select a specified `app` with the paramater `-app <app-label>`. For example, 
to deploy the `frontend` app from the `monorepo-project`, run 
`waypoint deploy -app frontend`.
The `-app` flag is a global target, and can be used with all Waypoint 
commands.
```

2021-02-23 05:03 UTC, vebr commented
Thank you for correcting my words @krantzinator

2021-02-23 12:08 UTC, vebr reviewed
LGTM!

2021-02-23 15:31 UTC, DerekStrickland commented on website/content/docs/waypoint-hcl/app.mdx
>  applications in your project. An example where this might be useful is
```suggestion
applications in your project. Some examples where this might be useful are
```

2021-02-23 15:32 UTC, DerekStrickland commented on website/content/docs/waypoint-hcl/app.mdx
> +separate backend and frontend processes or with a project that is a monorepo.
```suggestion
a deployment that targets multiple application tiers, a project that is part of a monorepo, or applications that require lock-step deployment.
```

2021-02-23 15:33 UTC, DerekStrickland commented on website/content/docs/waypoint-hcl/app.mdx
> +project = "monorepo-project"
```suggestion
project = "multi-tier-project"
```

2021-02-23 15:33 UTC, DerekStrickland commented on website/content/docs/waypoint-hcl/app.mdx
> +to deploy the `frontend` app from the `monorepo-project`, run
```suggestion
to deploy the `frontend` app from the `multi-tier-project`, run 
```

2021-02-24 14:56 UTC, krantzinator approved these changes
Looks great! lmk what you think @DerekStrickland 🙌🏻

2021-02-25 00:14 UTC, DerekStrickland approved these changes
LGTM

2021-02-25 19:41 UTC, merged